#!/bin/bash

# WRITE A SCRIPT (1 of 2) - Write a simple bash script that performs two actions:
# 1. Uploads a file (image, PDF, etc.) to a private bucket.
# 2. Presigns a URL to that file with an expiration of 604800 (7 days).
# 3. Write the script so that it takes three positional arguments: The name of t>

if [ "$#" -ne 3 ]; then
        echo "Incorrect Number of Inputs"
        exit 1
fi

file_to_upload="$1"
bucket_name="$2"
expiration_time="$3"

aws s3 cp $file_to_upload s3://$bucket/
aws s3 presign --expires-in $expiration_secs s3://$bucket/$file_to_upload

#Final Input: ./lab4_script1.sh flag.jpeg ds2002-kyj7zq 604800
